export interface WalletAccount{address:string;publicKey:string;scheme:string;path:string}
export interface Vault{kind:string;version:number;address:string;scheme:string;path:string;kdf:{name:string;hash:string;iterations:number};cipher:string;salt:string;iv:string;data:string}
export const VAULT_KEY='qtc-market.wallet.v1';
export class WalletClient{
 private worker:Worker;private seq=0;private closed=false;private pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
 constructor(){this.worker=new Worker('/crypto/wallet-worker.js',{type:'module'});this.worker.onmessage=e=>{const p=this.pending.get(e.data.id);if(p){clearTimeout(p.timer);this.pending.delete(e.data.id);e.data.ok?p.resolve(e.data.result):p.reject(new Error(e.data.error))}};this.worker.onerror=()=>this.close('本地钱包组件加载失败，请刷新页面后重试。');}
 request<T>(type:string,rest:Record<string,unknown>={}):Promise<T>{if(this.closed)return Promise.reject(new Error('钱包已锁定。'));return new Promise((resolve,reject)=>{const id=++this.seq,timer=setTimeout(()=>this.close('钱包操作超时，请重新解锁。'),90000);this.pending.set(id,{resolve,reject,timer});this.worker.postMessage({...rest,type,id})})}
 close(reason='钱包已锁定。'){if(this.closed)return;this.closed=true;this.worker.terminate();for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error(reason))}this.pending.clear()}
}
export function saveVault(v:Vault){const raw=JSON.stringify(v);localStorage.setItem(VAULT_KEY,raw);if(localStorage.getItem(VAULT_KEY)!==raw)throw new Error('浏览器无法保存钱包，请检查存储权限。')}
export function readVault():Vault|null{const raw=localStorage.getItem(VAULT_KEY);if(!raw)return null;if(raw.length>12000)throw new Error('本地钱包文件异常。');const v=JSON.parse(raw);if(v.kind!=='qtc-market-wallet'||v.version!==1)throw new Error('本地钱包版本不受支持。');return v;}
export async function readBalance(address:string){const r=await fetch('https://sqm.quantus.com/v1/graphql',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:'query Balance($id:String!){account:account_by_pk(id:$id){free reserved frozen} stats:chain_stats_by_pk(id:"global"){block_height}}',variables:{id:address}}),credentials:'omit',referrerPolicy:'no-referrer',redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('余额查询暂不可用。');const j=await r.json() as {errors?:unknown;data?:{account?:{free?:string;reserved?:string;frozen?:string};stats?:{block_height:number}}};if(j.errors||!j.data?.stats)throw new Error('无法取得余额。');const free=j.data.account?.free??'0';if(!/^\d+$/.test(free))throw new Error('余额格式不正确。');return{free,block:j.data.stats.block_height}}
